=== re-motion/Framework/Remotion/Data/DomainObjects/Schemas/Queries.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema 
    xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    xmlns:q="http://www.re-motion.org/Data/DomainObjects/Queries/2.0"
    xmlns:t="http://www.re-motion.org/Data/DomainObjects/Types" 
    elementFormDefault="qualified" 
    attributeFormDefault="unqualified" 
    targetNamespace="http://www.re-motion.org/Data/DomainObjects/Queries/2.0"
    xml:lang="en">

  <!-- TODO: Import should contain schemaLocation to ensure application developer can check its mapping during design time. 
             Before this is done it should be verified that schemaLocation there is no problem when XSD is used as embedded ressource during run time. -->
  <xs:import namespace="http://www.re-motion.org/Data/DomainObjects/Types" />

  <xs:element name="queries">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="query" type="q:queryType" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>

    <xs:key name="queryKey">
      <xs:selector xpath="q:query" />
      <xs:field xpath="@id" />
    </xs:key>

  </xs:element>

  <xs:complexType name="queryType">
    <xs:sequence>
      <xs:element name="storageGroupType" type="t:requiredStringType" minOccurs="0" />
      <xs:element name="statement" type="t:requiredStringType" />
      <xs:element name="collectionType" type="t:requiredStringType" minOccurs="0" />
    </xs:sequence>
    <xs:attribute name="id" type="t:requiredStringType" use="required" />
    <xs:attribute name="type" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="collection-readonly" />
          <xs:enumeration value="scalar-readonly" />
          <xs:enumeration value="custom-readonly" />
          <xs:enumeration value="collection-readwrite" />
          <xs:enumeration value="scalar-readwrite" />
          <xs:enumeration value="custom-readwrite" />
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="statementType" use="optional">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="text" />
          <xs:enumeration value="stored-procedure" />
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>
</xs:schema>

=== re-motion/Framework/Remotion/Data/DomainObjects.UnitTests/QueriesForLoaderTest.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!-- This file is part of the re-motion Core Framework (www.re-motion.org)
 ! Copyright (c) rubicon IT GmbH, www.rubicon.eu
 ! 
 ! The re-motion Core Framework is free software; you can redistribute it 
 ! and/or modify it under the terms of the GNU Lesser General Public License 
 ! as published by the Free Software Foundation; either version 2.1 of the 
 ! License, or (at your option) any later version.
 ! 
 ! re-motion is distributed in the hope that it will be useful, 
 ! but WITHOUT ANY WARRANTY; without even the implied warranty of 
 ! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
 ! GNU Lesser General Public License for more details.
 ! 
 ! You should have received a copy of the GNU Lesser General Public License
 ! along with re-motion; if not, see http://www.gnu.org/licenses.
-->
<queries 
    xmlns="http://www.re-motion.org/Data/DomainObjects/Queries/2.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.re-motion.org/Data/DomainObjects/Queries/2.0 ..\DomainObjects\Schemas\Queries.xsd">

  <query id="OrderQueryWithCustomCollectionType" type="collection-readonly">
    <storageGroupType>Remotion.Data.DomainObjects.UnitTests::TestDomain.TestDomainAttribute</storageGroupType>
    <statement>select [Order].* from [Order] inner join [Company] where [Company].[ID] = @customerID order by [OrderNo] asc;</statement>
    <collectionType>Remotion.Data.DomainObjects.UnitTests.TestDomain.OrderCollection, Remotion.Data.DomainObjects.UnitTests</collectionType>
  </query>

  <query id="OrderQueryWithObjectListOfOrder" type="collection-readonly">
    <storageGroupType>Remotion.Data.DomainObjects.UnitTests::TestDomain.TestDomainAttribute</storageGroupType>
    <statement>select [Order].* from [Order] inner join [Company] where [Company].[ID] = @customerID order by [OrderNo] asc;</statement>
    <collectionType>Remotion.Data.DomainObjects.ObjectList`1[[Remotion.Data.DomainObjects.UnitTests.TestDomain.Order, Remotion.Data.DomainObjects.UnitTests]], Remotion.Data.DomainObjects</collectionType>
  </query>

  <query id="CustomerTypeQuery" type="collection-readonly">
    <storageGroupType>Remotion.Data.DomainObjects.UnitTests::TestDomain.TestDomainAttribute</storageGroupType>
    <statement>select [Company].* from [Company] where [CustomerType] = @customerType order by [Name] asc;</statement>
  </query>

  <query id="OrderSumQueryWithQueryTypeScalarReadOnly" type="scalar-readonly">
    <storageGroupType>Remotion.Data.DomainObjects.UnitTests::TestDomain.TestDomainAttribute</storageGroupType>
    <statement>select sum(quantity) from [Order] where [CustomerID] = @customerID;</statement>
  </query>

  <query id="OrderSumQueryWithQueryTypeCustomReadOnly" type="custom-readonly">
    <storageGroupType>Remotion.Data.DomainObjects.UnitTests::TestDomain.TestDomainAttribute</storageGroupType>
    <statement>select sum(quantity) from [Order] where [CustomerID] = @customerID;</statement>
  </query>

  <query id="TestQueryDefinitionWithQueryTypeCollectionReadWrite" type="collection-readwrite" statementType="text">
    <storageGroupType>Remotion.Data.DomainObjects.UnitTests::TestDomain.TestDomainAttribute</storageGroupType>
    <statement>select [Company].* from [Company] where [CustomerType] = @customerType order by [Name] asc;</statement>
  </query>

  <query id="TestQueryDefinitionWithQueryTypeScalarReadWrite" type="scalar-readwrite" statementType="text">
    <storageGroupType>Remotion.Data.DomainObjects.UnitTests::TestDomain.TestDomainAttribute</storageGroupType>
    <statement>select 0;</statement>
  </query>

  <query id="TestQueryDefinitionWithQueryTypeCustomReadWrite" type="custom-readwrite" statementType="text">
    <storageGroupType>Remotion.Data.DomainObjects.UnitTests::TestDomain.TestDomainAttribute</storageGroupType>
    <statement>select 0;</statement>
  </query>

  <query id="TestStoredProcedureQuery" type="collection-readonly" statementType="stored-procedure">
    <storageGroupType>Remotion.Data.DomainObjects.UnitTests::TestDomain.TestDomainAttribute</storageGroupType>
    <statement>rpf_testSPQuery</statement>
    <collectionType>Remotion.Data.DomainObjects.UnitTests.TestDomain.OrderCollection, Remotion.Data.DomainObjects.UnitTests</collectionType>
  </query>
</queries>

=== re-motion/Framework/Remotion/Data/DomainObjects.UnitTests/QueriesForLoaderTestDuplicate.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!-- This file is part of the re-motion Core Framework (www.re-motion.org)
 ! Copyright (c) rubicon IT GmbH, www.rubicon.eu
 ! 
 ! The re-motion Core Framework is free software; you can redistribute it 
 ! and/or modify it under the terms of the GNU Lesser General Public License 
 ! as published by the Free Software Foundation; either version 2.1 of the 
 ! License, or (at your option) any later version.
 ! 
 ! re-motion is distributed in the hope that it will be useful, 
 ! but WITHOUT ANY WARRANTY; without even the implied warranty of 
 ! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
 ! GNU Lesser General Public License for more details.
 ! 
 ! You should have received a copy of the GNU Lesser General Public License
 ! along with re-motion; if not, see http://www.gnu.org/licenses.
-->
<queries 
    xmlns="http://www.re-motion.org/Data/DomainObjects/Queries/2.0" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.re-motion.org/Data/DomainObjects/Queries/2.0 ..\DomainObjects\Schemas\Queries.xsd">

  <query id="OrderQueryWithCustomCollectionType" type="collection-readonly">
    <storageGroupType>Remotion.Data.DomainObjects.UnitTests::TestDomain.TestDomainAttribute</storageGroupType>
    <statement>select [Order].* from [Order] inner join [Company] where [Company].[ID] = @customerID order by [OrderNo] asc;</statement>
    <collectionType>Remotion.Data.DomainObjects.UnitTests.TestDomain.OrderCollection, Remotion.Data.DomainObjects.UnitTests</collectionType>
  </query>

  <query id="OrderQueryWithObjectListOfOrder" type="collection-readonly">
    <storageGroupType>Remotion.Data.DomainObjects.UnitTests::TestDomain.TestDomainAttribute</storageGroupType>
    <statement>select [Order].* from [Order] inner join [Company] where [Company].[ID] = @customerID order by [OrderNo] asc;</statement>
    <collectionType>Remotion.Data.DomainObjects.ObjectList`1[[Remotion.Data.DomainObjects.UnitTests.TestDomain.Order, Remotion.Data.DomainObjects.UnitTests]], Remotion.Data.DomainObjects</collectionType>
  </query>

  <query id="CustomerTypeQuery" type="collection-readonly">
    <storageGroupType>Remotion.Data.DomainObjects.UnitTests::TestDomain.TestDomainAttribute</storageGroupType>
    <statement>select [Company].* from [Company] where [CustomerType] = @customerType order by [Name] asc;</statement>
  </query>

  <query id="OrderSumQuery" type="scalar-readonly">
    <storageGroupType>Remotion.Data.DomainObjects.UnitTests::TestDomain.TestDomainAttribute</storageGroupType>
    <statement>select sum(quantity) from [Order] where [CustomerID] = @customerID;</statement>
  </query>

</queries>

=== re-motion/Framework/Remotion/Data/DomainObjects.UnitTests/QueriesForLoaderTest2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-- This file is part of the re-motion Core Framework (www.re-motion.org)
 ! Copyright (c) rubicon IT GmbH, www.rubicon.eu
 ! 
 ! The re-motion Core Framework is free software; you can redistribute it 
 ! and/or modify it under the terms of the GNU Lesser General Public License 
 ! as published by the Free Software Foundation; either version 2.1 of the 
 ! License, or (at your option) any later version.
 ! 
 ! re-motion is distributed in the hope that it will be useful, 
 ! but WITHOUT ANY WARRANTY; without even the implied warranty of 
 ! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
 ! GNU Lesser General Public License for more details.
 ! 
 ! You should have received a copy of the GNU Lesser General Public License
 ! along with re-motion; if not, see http://www.gnu.org/licenses.
-->
<queries 
    xmlns="http://www.re-motion.org/Data/DomainObjects/Queries/1.0" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.re-motion.org/Data/DomainObjects/Queries/1.0 ..\DomainObjects\Schemas\Queries.xsd">

  <query id="OrderQueryWithCustomCollectionType2" type="collection">
    <storageGroupType>Remotion.Data.DomainObjects.UnitTests::TestDomain.TestDomainAttribute</storageGroupType>
    <statement>select [Order].* from [Order] inner join [Company] where [Company].[ID] = @customerID order by [OrderNo] asc;</statement>
    <collectionType>Remotion.Data.DomainObjects.UnitTests.TestDomain.OrderCollection, Remotion.Data.DomainObjects.UnitTests</collectionType>
  </query>

  <query id="OrderQueryWithObjectListOfOrder2" type="collection">
    <storageGroupType>Remotion.Data.DomainObjects.UnitTests::TestDomain.TestDomainAttribute</storageGroupType>
    <statement>select [Order].* from [Order] inner join [Company] where [Company].[ID] = @customerID order by [OrderNo] asc;</statement>
    <collectionType>Remotion.Data.DomainObjects.ObjectList`1[[Remotion.Data.DomainObjects.UnitTests.TestDomain.Order, Remotion.Data.DomainObjects.UnitTests]], Remotion.Data.DomainObjects</collectionType>
  </query>

  <query id="CustomerTypeQuery2" type="collection">
    <storageGroupType>Remotion.Data.DomainObjects.UnitTests::TestDomain.TestDomainAttribute</storageGroupType>
    <statement>select [Company].* from [Company] where [CustomerType] = @customerType order by [Name] asc;</statement>
  </query>

  <query id="OrderSumQuery2" type="scalar">
    <storageGroupType>Remotion.Data.DomainObjects.UnitTests::TestDomain.TestDomainAttribute</storageGroupType>
    <statement>select sum(quantity) from [Order] where [CustomerID] = @customerID;</statement>
  </query>

</queries>
